## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


In [ ]:
import pandas as pd
import numpy as np

**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
#1-1
people = pd.DataFrame(data, columns=["name", "job", "family_size", "num_cars"])

#1-2
print(people[(people["job"].isin(["psychologist", "teacher"]))  & (people["num_cars"] > people["family_size"])])

#1-3
print(people[(people["num_cars"] >= 1) & (people['family_size'] <= 2)])

#1-4
print(len(people.job.unique()), "unique jobs")


   name           job  family_size  num_cars
5  Lisa  psychologist            3         4
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1
4 unique jobs


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
food = pd.DataFrame({"fruit" : fruit, "weight" : weights})
print("Mean weight for apple is", food[(food["fruit"] == "apple")].mean())
print("Mean weight for carrot is", food[(food["fruit"] == "carrot")].mean())
print("Mean weight for banana is", food[(food["fruit"] == "banana")].mean())


Mean weight for apple is weight    4.2
dtype: float64
Mean weight for carrot is weight    6.333333
dtype: float64
Mean weight for banana is weight    7.5
dtype: float64


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
#3-1
courses = pd.Series(course_name).sort_values(ascending=True)
print(courses.index)

#3-2
ps = []
for word in courses:
  if word[0] == "P":
    ps.append("True")
  else:
    ps.append("False")
print(ps)

Int64Index([1, 3, 0, 2, 4], dtype='int64')
['False', 'True', 'True', 'False', 'False']


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
#4-1
reverse = student_id[::-1]
print(student_id)
print(reverse)

#4-2
sorted = np.sort(student_id)
print("Largest Values:", sorted[-3:])

[1023 1671 1682 4532 5202 5241 6230]
[6230 5241 5202 4532 1682 1671 1023]
Largest Values: [5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
nums = np.arange(1,100)
multiples = nums[(nums % 3 == 0) | (nums % 5 == 0)]
print(multiples)
print("Sum is", multiples.sum())

# Hint: you can use arange to start off

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
Sum is 2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#6-1
columnSwap = arr
columnSwap[:, [0,1]] = arr[:, [1,0]]
print(columnSwap)

#6-2
rowSwap = arr
rowSwap[[0,1],:] = arr[[1,0],:]
print(rowSwap)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
